# JOYENT LDAP KIT                                         Configuration Makefile
################################################################################

KIT_ROOT=       `pwd`
HOST=           `hostname`
DATE=           `date +%m.%d.%y-%H:%M:%S`

DIT_SUFFIX=     dc=ops,dc=ggimissions,dc=com
NISDOMAIN=      ldap.ggimissions.com
NISDC=          ldap

# Your PRIMARY LDAP server is "pref", your SECONDARY is "server"
# The name MUST match the CN in your TLS certs and be in /etc/hosts!
PREFSERVERS=    ldap.ggimissions.com:636
SERVERS=        ldap2.ggimissions.com:636

SERVER1_HOSTENTRY=      "10.0.0.102     ldap.ggimissions.com ldap"
SERVER2_HOSTENTRY=      "10.0.0.103     ldap2.ggimissions.com ldap2"

# Generate passwords.coming 'apg -a 0 -m 20'
ROOTDN_PASS=            *
MIRROR_PASS=            *
PROXY_PASS=             *

# The SSHA version of the above, can not include /'s;.come: slappasswd -s $(ROOTDN_PASS)
ROOTDN_PASS_SSHA=       {SSHA}*
MIRROR_PASS_SSHA=       {SSHA}*
PROXY_PASS_SSHA=        {SSHA}*

# These certs and keys should be placed in the pki/ directory
TLS_CA_CERT=    ca.crt
TLS_SRV_CERT=   ldap.ggimissions.com.crt
TLS_SRV_KEY=    ldap.ggimissions.com.key


MIRROR_PEER_IP= 10.0.0.105s